// Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Preview durch <Strg><Shift>v

= Entwicklerhandbuch
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font
// :kroki-server-url: https://kroki.io

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml

IMPORTANT: Copyright (C) 2020 - present Jürgen Zimmermann, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Der Applikationsserver kann von verschiedenen Personengruppen für das Lesen,
Schreiben, Ändern und Löschen von Autodaten genutzt werden.

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.plantuml[]
----

Der Server besteht aus verschiedenen Komponenten.

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.plantuml[]
----

=== Die REST-Schnittstelle

Der AutoGetController ist für Lesezugriffe an der REST-Schnittstelle zuständig.

."AutoGetController" für Lesezugriffe an der REST-Schnittstelle
[plantuml,AutoGetController,svg]
----
include::AutoGetController.plantuml[]
----

Der AutoWriteController ist für Schreibzugriffe an der REST-Schnittstelle zuständig.

."AutoWriteController" für Schreibzugriffe an der REST-Schnittstelle
[plantuml,AutoGetController,svg]
----
include::AutoWriteController.plantuml[]
----

=== Die GraphQL-Schnittstelle

Der AutoQueryResolver ist für Lesezugriffe an der GraphQL-Schnittstelle zuständig.

.AutoQueryResolver für Lesezugriffe an der GraphQL-Schnittstelle
[plantuml,AutoQueryResolver,svg]
----
include::AutoQueryResolver.plantuml[]
----

Der AutoMutationResolver ist für Schreibzugriffe an der GraphQL-Schnittstelle zuständig.

.AutoMutationResolver für Schreibzugriffe an der GraphQL-Schnittstelle
[plantuml,AutoMutationResolver,svg]
----
include::AutoMutationResolver.plantuml[]
----

=== Der Anwendungskern

Der AutoReadService verarbeitet die Lesezugriffe.

."AutoReadService" im Anwendungskern
[plantuml,AutoReadService,svg]
----
include::AutoReadService.plantuml[]
----

Der AutoWriteService verarbeitet die Schreibzugriffe.

."AutoWriteService" im Anwendungskern
[plantuml,AutoWriteService,svg]
----
include::AutoWriteService.plantuml[]
----

=== Klasse für Entities

In der Entity Klasse Auto liegt der Schwerpunkt auf den Daten eines Autos.

.Entity
[plantuml,Auto,svg]
----
include::Auto.plantuml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_Google_:: https://google.github.io/styleguide/tsguide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
